# remote_theme: pages-themes/tactile@v0.2.0
# plugins:
# - jekyll-remote-theme
title: Ameer Majeed
description: Wannabe Computer Scientist / History Freak
logo: image.png
email: ameer.ha.majeed@gmail.com
twitter_username: ameermajeedcv
github_username: ameermajeed
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme 
